NUM_DISTINCT_CARDS = 46

# Generic / Shared Action numbers
GEN_CRAFT_CARD = 0
GEN_DISCARD_CARD = GEN_CRAFT_CARD + 34 # 34 cards craftable in standard way
GEN_USE_AMBUSH = GEN_DISCARD_CARD + NUM_DISTINCT_CARDS # of cards in the deck
GEN_CRAFT_SABOTEURS = GEN_USE_AMBUSH + 5
GEN_CRAFT_CORVID_PLANNERS = GEN_CRAFT_SABOTEURS + 3
GEN_CRAFT_BOAT_BUILDERS = GEN_CRAFT_CORVID_PLANNERS + 6
GEN_CRAFT_PROP_BUREAU = GEN_CRAFT_BOAT_BUILDERS + 6
GEN_EFFECTS_NONE = GEN_CRAFT_PROP_BUREAU + 10
GEN_EFFECTS_PARTISANS = GEN_EFFECTS_NONE + 1
GEN_USE_SABOTEURS = GEN_EFFECTS_PARTISANS + 3
GEN_SABO_TARGET_CARD = GEN_USE_SABOTEURS + 3
GEN_SWAP_MEET = GEN_SABO_TARGET_CARD + 18
GEN_START_FALSE_ORDERS = GEN_SWAP_MEET + 3
GEN_END_FALSE_ORDERS = GEN_START_FALSE_ORDERS + 36
GEN_GIVE_AWAY_CARD = GEN_END_FALSE_ORDERS + 12
GEN_START_PROP_BUREAU = GEN_GIVE_AWAY_CARD + NUM_DISTINCT_CARDS
GEN_CHARM_OFFENSIVE = GEN_START_PROP_BUREAU + 36
GEN_USE_INFORMANTS = GEN_CHARM_OFFENSIVE + 3


GEN_SKIP_MOVE = 
GEN_ACTIVATE_DOMINANCE = GEN_SKIP_MOVE + 1
GEN_TAKE_DOMINANCE = GEN_ACTIVATE_DOMINANCE + 4
GEN_END_TURN = GEN_TAKE_DOMINANCE + 4
# Non-VB actions
GEN_MOVE_CLEARINGS = GEN_END_TURN + 1
GEN_MOVE_AMOUNT = GEN_MOVE_CLEARINGS + 144


# Marquise de Cat Action Numbers
MC_PLACE_KEEP = GEN_MOVE_AMOUNT + 25
MC_PLACE_WOOD = MC_PLACE_KEEP + 12
MC_BATTLE_EYRIE = MC_PLACE_WOOD + 12
MC_BATTLE_ALLIANCE = MC_BATTLE_EYRIE + 12
MC_BATTLE_VAGABOND = MC_BATTLE_ALLIANCE + 12
MC_BUILD_SAWMILL = MC_BATTLE_VAGABOND + 12
MC_BUILD_WORKSHOP = MC_BUILD_SAWMILL + 12
MC_BUILD_RECRUITER = MC_BUILD_WORKSHOP + 12
MC_SPEND_BIRD_CARD = MC_BUILD_RECRUITER + 12
MC_RECRUIT = MC_SPEND_BIRD_CARD + 10
MC_ORDER_KEEP = MC_RECRUIT + 1
MC_ORDER_WOOD = MC_ORDER_KEEP + 1
MC_ORDER_SAWMILL = MC_ORDER_WOOD + 1
MC_ORDER_WORKSHOP = MC_ORDER_SAWMILL + 1
MC_ORDER_RECRUITER = MC_ORDER_WORKSHOP + 1
MC_OVERWORK_CLEARING = MC_ORDER_RECRUITER + 1
MC_SKIP_FH = MC_OVERWORK_CLEARING + 12
MC_FIELD_HOSPITALS = MC_SKIP_FH + 1
MC_CHOOSE_OUTRAGE = MC_FIELD_HOSPITALS + NUM_DISTINCT_CARDS
MC_RECRUIT_LOCATION = MC_CHOOSE_OUTRAGE + NUM_DISTINCT_CARDS
MC_SPEND_WOOD = MC_RECRUIT_LOCATION + 12
MC_SKIP_TO_DAY = MC_SPEND_WOOD + 12
MC_USE_BBB = MC_SKIP_TO_DAY + 1
MC_USE_STAND_DELIVER = MC_USE_BBB + 3
MC_SKIP_CRAFTING = MC_USE_STAND_DELIVER + 3
MC_SKIP_TO_EVENING = MC_SKIP_CRAFTING + 1
MC_USE_CODEBREAKERS = MC_SKIP_TO_EVENING + 1

# Eyrie Dynasties Action Numbers
EY_RECRUIT_LOCATION = GEN_MOVE_AMOUNT + 25
EY_BUILD_LOCATION = EY_RECRUIT_LOCATION + 12
EY_BATTLE_MARQUISE = EY_BUILD_LOCATION + 12
EY_BATTLE_ALLIANCE = EY_BATTLE_MARQUISE + 12
EY_BATTLE_VAGABOND = EY_BATTLE_ALLIANCE + 12
EY_CHOOSE_LEADER = EY_BATTLE_VAGABOND + 12
EY_DECREE_RECRUIT = EY_CHOOSE_LEADER + 4
EY_DECREE_MOVE = EY_DECREE_RECRUIT + 4
EY_DECREE_BATTLE = EY_DECREE_MOVE + 4
EY_DECREE_BUILD = EY_DECREE_BATTLE + 4
EY_DECREE_CARD = EY_DECREE_BUILD + 4
EY_A_NEW_ROOST = EY_DECREE_CARD + NUM_DISTINCT_CARDS
EY_CHOOSE_OUTRAGE = EY_A_NEW_ROOST + 12
EY_USE_BBB = EY_CHOOSE_OUTRAGE + NUM_DISTINCT_CARDS
EY_USE_STAND_DELIVER = EY_USE_BBB + 3
EY_USE_CODEBREAKERS = EY_USE_STAND_DELIVER + 3
EY_SKIP_TO_DAY = EY_USE_CODEBREAKERS + 3
EY_SKIP_2ND_DECREE = EY_SKIP_TO_DAY + 1
EY_SKIP_CRAFTING = EY_SKIP_2ND_DECREE + 1
EY_SKIP_TO_EVENING = EY_SKIP_CRAFTING + 1

# Woodland Alliance Action Numbers
WA_RECRUIT_LOCATION = GEN_MOVE_AMOUNT + 25
WA_REVOLT_LOCATION = WA_RECRUIT_LOCATION + 12
WA_ORGANIZE_LOCATION = WA_REVOLT_LOCATION + 12
WA_BATTLE_MARQUISE = WA_ORGANIZE_LOCATION + 12
WA_BATTLE_EYRIE = WA_BATTLE_MARQUISE + 12
WA_BATTLE_VAGABOND = WA_BATTLE_EYRIE + 12
WA_DISCARD_SUPPORTER = WA_BATTLE_VAGABOND + 12
WA_SPREAD_SYMPATHY = WA_DISCARD_SUPPORTER + NUM_DISTINCT_CARDS
WA_MOBILIZE = WA_SPREAD_SYMPATHY + 12
WA_TRAIN_OFFICER = WA_MOBILIZE + NUM_DISTINCT_CARDS
WA_USE_BBB = WA_TRAIN_OFFICER + NUM_DISTINCT_CARDS
WA_USE_STAND_DELIVER = WA_USE_BBB + 3
WA_USE_CODEBREAKERS = WA_USE_STAND_DELIVER + 3
WA_SKIP_TO_DAY = WA_USE_CODEBREAKERS + 3
WA_SKIP_REVOLTING = WA_SKIP_TO_DAY + 1
WA_SKIP_TO_EVENING = WA_SKIP_REVOLTING + 1
WA_SKIP_MILITARY_OPS = WA_SKIP_TO_EVENING + 1
WA_ORDER_SYMPATHY = WA_SKIP_MILITARY_OPS + 1
WA_ORDER_BASE = WA_ORDER_SYMPATHY + 1

# Vagabond Action Numbers
VB_BATTLE_MARQUISE = GEN_END_TURN + 1
VB_BATTLE_EYRIE = VB_BATTLE_MARQUISE + 12
VB_BATTLE_ALLIANCE = VB_BATTLE_EYRIE + 12
VB_USE_BBB = VB_BATTLE_ALLIANCE + 12
VB_USE_STAND_DELIVER = VB_USE_BBB + 3
VB_USE_CODEBREAKERS = VB_USE_STAND_DELIVER + 3
VB_CHOOSE_OUTRAGE = VB_USE_CODEBREAKERS + 3
VB_CHOOSE_CLASS = VB_CHOOSE_OUTRAGE + NUM_DISTINCT_CARDS
VB_REFRESH_UNDAM = VB_CHOOSE_CLASS + 3
VB_REFRESH_DAM = VB_REFRESH_UNDAM + 8
VB_MOVE = VB_REFRESH_DAM + 8
VB_EXPLORE = VB_MOVE + 19
VB_START_AIDING = VB_EXPLORE + 1
VB_CHOOSE_AID_EXHAUST = VB_START_AIDING + 126
VB_CHOOSE_AID_TAKE = VB_CHOOSE_AID_EXHAUST + 8
VB_COMPLETE_QUEST = VB_CHOOSE_AID_TAKE + 8
VB_STRIKE = VB_COMPLETE_QUEST + 30
VB_REPAIR_UNEXH = VB_STRIKE + 13
VB_REPAIR_EXH = VB_REPAIR_UNEXH + 8
VB_THIEF_ABILITY = VB_REPAIR_EXH + 8
VB_TINKER_ABILITY = VB_THIEF_ABILITY + 3
VB_RANGER_ABILITY = VB_TINKER_ABILITY + NUM_DISTINCT_CARDS
VB_DISCARD_ITEM = VB_RANGER_ABILITY + 1
VB_DAMAGE_UNEXH = VB_DISCARD_ITEM + 32
VB_DAMAGE_EXH = VB_DAMAGE_UNEXH + 8
VB_ACTIVATE_COALITION = VB_DAMAGE_EXH + 8
VB_NO_ALLY_MOVE = VB_ACTIVATE_COALITION + 12
VB_MARQUISE_ALLY_MOVE = VB_NO_ALLY_MOVE + 1
VB_EYRIE_ALLY_MOVE = VB_MARQUISE_ALLY_MOVE + 25
VB_ALLIANCE_ALLY_MOVE = VB_EYRIE_ALLY_MOVE + 20
VB_BATTLE_WITH_ALLY = VB_ALLIANCE_ALLY_MOVE + 10
VB_BATTLE_ALLY_HITS = VB_BATTLE_WITH_ALLY + 4
VB_SKIP_TO_DAY = VB_BATTLE_ALLY_HITS + 3
VB_SKIP_TO_EVENING = VB_SKIP_TO_DAY + 1